PR - Kittenservice to dev
WildCodeSchool/library-management pull request #14
Opened 2024-06-29 13:40 UTC by carlsavila

kittenservice implementation with the kitttens list display.

2024-07-02 13:31 UTC, Benja-san requested changes

2024-07-02 13:31 UTC, Benja-san commented on src/app/components/kitten/kitten/kitten.component.scss
> +/* Medium devices (landscape tablets, 768px and up) */
remove dead code

2024-07-02 13:31 UTC, Benja-san commented on src/app/components/kitten/kitten/kitten.component.scss
> +    /* Kittend Card */
remove dead code

2024-07-02 13:31 UTC, Benja-san commented on src/app/components/kitten/kitten/kitten.component.scss
> +/* Extra large devices (large laptops and desktops, 1200px and up) */
remove dead code

2024-07-02 13:31 UTC, Benja-san commented on src/app/components/kitten/kitten/kitten.component.scss
> +    /* Kittend Card */
remove dead code

2024-07-02 13:31 UTC, Benja-san commented on src/app/model/animal/animal.ts
> +        console.log("compteur : " + Animal.getKittNumber() +  ". id "+  this.name + " " + this.id);
remove console log

2024-07-02 13:31 UTC, Benja-san commented on src/app/pages/kittens/kittens.component.html
> +        <h3>Chatons disponibles</h3>
page starts with azn H1

2024-07-02 13:31 UTC, Benja-san commented on src/app/pages/kittens/kittens.component.html
> +                        <app-kitten [kittenCard]="kitten"></app-kitten>
and organize H5 tag inside this component to be a logical suit to the previous h in this page

2024-07-02 13:31 UTC, Benja-san commented on src/app/pages/kittens/kittens.component.html
> +        <!--<button (click)="pushKittenForTest()"> ajouter</button>-->
remove dead code

2024-07-02 13:31 UTC, Benja-san commented on src/app/pages/kittens/kittens.component.html
> +    <!-- AVAILABLE kittens section -->
remove dead code

2024-07-02 13:31 UTC, Benja-san commented on src/app/pages/kittens/kittens.component.html
> +                        <!-- Card @Input -->
remove dead code

2024-07-02 13:31 UTC, Benja-san commented on src/app/pages/kittens/kittens.component.html
> +    <!-- USER section - user's kittens list
remove dead code

2024-07-02 13:31 UTC, Benja-san commented on src/app/pages/kittens/kittens.component.scss
> +/****** LIST in main ****/
remove dead code

2024-07-02 13:31 UTC, Benja-san commented on src/app/pages/kittens/kittens.component.scss
> +    //border: .1px solid greenyellow; // For DEBUGGING pourpose. to remove
remove dead code

2024-07-02 13:31 UTC, Benja-san commented on src/app/pages/kittens/kittens.component.scss
> +        //border: 5px solid fuchsia; // For DEBUGGING pourpose. to remove
remove dead code

2024-07-02 13:31 UTC, Benja-san commented on src/app/pages/kittens/kittens.component.scss
> +            //border: var(--grid-itemList-CardsContainer-boder); // For DEBUGGING pourpose. to remove
remove dead code

2024-07-02 13:31 UTC, Benja-san commented on src/app/pages/kittens/kittens.component.scss
> +    /* User Kitten List */
remove dead code

2024-07-02 13:31 UTC, Benja-san commented on src/app/pages/kittens/kittens.component.scss
> +    /* end list */
remove dead code

2024-07-02 13:31 UTC, Benja-san commented on src/app/pages/kittens/kittens.component.scss
> + /*** https://www.w3schools.com/css/css_rwd_mediaqueries.asp ***/
remove dead code

2024-07-02 13:31 UTC, Benja-san commented on src/app/pages/kittens/kittens.component.scss
> +            /*end list*/
remove dead code

2024-07-02 13:31 UTC, Benja-san commented on src/app/pages/kittens/kittens.component.scss
> +/* Medium devices (landscape tablets, 768px and up) */
remove dead code

2024-07-02 13:31 UTC, Benja-san commented on src/app/pages/kittens/kittens.component.scss
> +    /** liste **/
remove dead code

2024-07-02 13:31 UTC, Benja-san commented on src/app/pages/kittens/kittens.component.scss
> +        /*end list*/
remove dead code

2024-07-02 13:31 UTC, Benja-san commented on src/app/pages/kittens/kittens.component.scss
> +/* Large devices (laptops/desktops, 992px and up) */
remove dead code

2024-07-02 13:31 UTC, Benja-san commented on src/app/pages/kittens/kittens.component.scss
> +    /** List **/
remove dead code

2024-07-02 13:31 UTC, Benja-san commented on src/app/pages/kittens/kittens.component.scss
> +        // For DEBUGGING pourpose. to remove
remove dead code

2024-07-02 13:31 UTC, Benja-san commented on src/app/pages/kittens/kittens.component.scss
> +        // section grid LIST available KITTENS //
remove dead code

2024-07-02 13:31 UTC, Benja-san commented on src/app/pages/kittens/kittens.component.scss
> +            //padding: .5rem;
remove dead code

2024-07-02 13:31 UTC, Benja-san commented on src/app/pages/kittens/kittens.component.scss
> +            // For DEBUGGING pourpose. to remove
remove dead code

2024-07-02 13:31 UTC, Benja-san commented on src/app/pages/kittens/kittens.component.scss
> +                    // For DEBUGGING pourpose. to remove
remove dead code

2024-07-02 13:31 UTC, Benja-san commented on src/app/pages/kittens/kittens.component.scss
> +        // section grid USER'S KITTENS //
remove dead code

2024-07-02 13:31 UTC, Benja-san commented on src/app/pages/kittens/kittens.component.scss
> +            // For DEBUGGING pourpose. to remove
remove dead code

2024-07-02 13:31 UTC, Benja-san commented on src/app/pages/kittens/kittens.component.scss
> +        // section grid FORME ADD A KITTEN //
remove dead code

2024-07-02 13:31 UTC, Benja-san commented on src/app/pages/kittens/kittens.component.ts
> +  // KittensService injection (to get, add available kittens and adopted user's kitten(s)).
remove dead code

2024-07-02 13:31 UTC, Benja-san commented on src/app/pages/kittens/kittens.component.ts
> +    console.log("Récupération Json Kittens : ")
remove console log

2024-07-02 13:31 UTC, Benja-san commented on src/app/pages/kittens/kittens.component.ts
> +  getServiceKittenJsonKittens(): void {
getKittens*

2024-07-02 13:31 UTC, Benja-san commented on src/app/pages/kittens/kittens.component.ts
> +  getServiceKittenAvailableKittens(): Animal[] {
getAvailableKittens*

2024-07-02 13:31 UTC, Benja-san commented on src/app/pages/kittens/kittens.component.ts
> +  // Function to add new kitten received from create-kitten's @Output, using the form
rm dead code

2024-07-02 13:31 UTC, Benja-san commented on src/app/pages/kittens/kittens.component.ts
> +  // Funnction to send the adopted kitten to the user
rm dead code

2024-07-02 13:31 UTC, Benja-san commented on src/app/pages/kittens/kittens.component.ts
> +    console.log("got index ", kittenIndex)
remove console log

2024-07-02 13:31 UTC, Benja-san commented on src/app/pages/kittens/kittens.component.ts
> +    // Searching the adopted kitten by id in available kittens list.
rm dead code

2024-07-02 13:31 UTC, Benja-san commented on src/app/pages/kittens/kittens.component.ts
> +          // Adding found kitten to the user's adopted kitten.
rm dead code

2024-07-02 13:31 UTC, Benja-san commented on src/app/pages/kittens/kittens.component.ts
> +          // Delete from list by element corresponding to the indexOfItem
rm dead code

2024-07-02 13:31 UTC, Benja-san commented on src/app/pages/kittens/kittens.component.ts
> +          console.log("kitten found ", kittenItem)
remove console log

2024-07-02 13:31 UTC, Benja-san commented on src/app/pages/kittens/kittens.component.ts
> +  getServiceKittenAdoptedKitten(): Animal[] {
getAdoptedKittens

2024-07-02 13:31 UTC, Benja-san commented on src/app/services/kittens.service.ts
> +  // List available Kittens.
remove dead code

2024-07-02 13:31 UTC, Benja-san commented on src/app/services/kittens.service.ts
> +  // List to manage user adopted  Kittens.
remove dead code

2024-07-02 13:31 UTC, Benja-san commented on src/app/services/kittens.service.ts
> +  // HttpClient Service injection to read json
remove dead code

2024-07-02 13:31 UTC, Benja-san commented on src/app/services/kittens.service.ts
> +  // Json Read
remove dead code

2024-07-02 13:31 UTC, Benja-san commented on src/app/services/kittens.service.ts
> +      // Json to read :
remove dead code

2024-07-02 13:31 UTC, Benja-san commented on src/app/services/kittens.service.ts
> +  private jsonIsRead = false;
start property by is if boolean use

2024-07-02 14:05 UTC, carlsavila commented
CR applied!

2024-07-02 15:37 UTC, carlsavila commented
CR applied, dev/kittenservice conflicts resolved

2024-07-03 14:03 UTC, Benja-san approved these changes

2024-07-03 14:10 UTC, merged